name: rust

on: [push, pull_request]

# Make sure CI fails on all warnings, including Clippy lints
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: '-Dwarnings'

jobs:
  clippy_check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Run Clippy
        run: |
          cargo clippy --all-targets --all-features --manifest-path=src-tauri/Cargo.toml

  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check formatting
        run: |
          cargo fmt --all --check --manifest-path=src-tauri/Cargo.toml
